# Generated by Django 2.2.7 on 2020-11-24 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_folder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='booklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisher', models.CharField(max_length=255, verbose_name='出版社')),
                ('name', models.CharField(max_length=255, verbose_name='書名')),
                ('author', models.CharField(max_length=255, verbose_name='著者')),
                ('price', models.CharField(max_length=255, verbose_name='単価')),
                ('detail', models.CharField(max_length=10000, verbose_name='詳細')),
                ('date', models.CharField(max_length=255, verbose_name='出版年月')),
                ('isbn', models.CharField(max_length=255, unique=True, verbose_name='ISBN')),
            ],
        ),
    ]
