# Generated by Django 2.2.7 on 2020-11-24 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_folder', '0002_booklist'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='booklist',
            new_name='BookListDB',
        ),
    ]
