# Generated by Django 2.2.7 on 2020-11-24 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_folder', '0003_auto_20201124_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booklistdb',
            name='detail',
            field=models.CharField(max_length=10001, verbose_name='詳細'),
        ),
    ]
