# Generated by Django 2.2.7 on 2020-11-24 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_folder', '0004_auto_20201124_1227'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booklistdb',
            old_name='name',
            new_name='title',
        ),
    ]
