# Generated by Django 2.2.7 on 2020-11-26 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_folder', '0007_auto_20201124_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booklistmodel',
            name='isbn',
            field=models.CharField(max_length=255, verbose_name='ISBN'),
        ),
    ]
