# Generated by Django 2.2.7 on 2020-12-15 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_folder', '0011_auto_20201215_1913'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='filename',
            new_name='title',
        ),
    ]
