# Generated by Django 2.2.7 on 2020-12-16 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_folder', '0014_auto_20201215_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
