# Generated by Django 2.2.7 on 2020-12-17 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_folder', '0015_upload_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisposalListModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_date', models.DateField(verbose_name='受入日')),
                ('reg_no', models.CharField(max_length=255, verbose_name='登録番号')),
                ('author', models.CharField(max_length=255, verbose_name='著者')),
                ('title', models.CharField(max_length=255, verbose_name='書名')),
                ('publisher', models.CharField(max_length=255, verbose_name='出版社')),
                ('price', models.CharField(max_length=255, verbose_name='本体価格')),
                ('pub_date', models.CharField(max_length=255, verbose_name='発行年')),
                ('class_no', models.CharField(max_length=255, verbose_name='分類番号')),
                ('disposal_date', models.DateField(verbose_name='廃棄日')),
                ('detail', models.CharField(max_length=10001, verbose_name='備考')),
                ('isbn', models.CharField(max_length=255, verbose_name='ISBN')),
            ],
        ),
        migrations.AlterField(
            model_name='upload',
            name='description',
            field=models.CharField(max_length=255, verbose_name='詳細'),
        ),
        migrations.AlterField(
            model_name='upload',
            name='file',
            field=models.CharField(max_length=100, verbose_name='url'),
        ),
    ]
