# Generated by Django 2.2.7 on 2020-12-18 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_folder', '0016_auto_20201217_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disposallistmodel',
            name='class_no',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='分類番号'),
        ),
        migrations.AlterField(
            model_name='disposallistmodel',
            name='detail',
            field=models.CharField(blank=True, max_length=10001, null=True, verbose_name='備考'),
        ),
        migrations.AlterField(
            model_name='disposallistmodel',
            name='disposal_date',
            field=models.DateField(blank=True, null=True, verbose_name='廃棄日'),
        ),
        migrations.AlterField(
            model_name='disposallistmodel',
            name='reg_date',
            field=models.DateField(blank=True, null=True, verbose_name='受入日'),
        ),
        migrations.AlterField(
            model_name='disposallistmodel',
            name='reg_no',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='登録番号'),
        ),
    ]
