# Generated by Django 2.2.7 on 2020-12-18 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_folder', '0017_auto_20201218_2239'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disposallistmodel',
            old_name='pub_date',
            new_name='date',
        ),
    ]
