# Generated by Django 2.2.7 on 2020-12-18 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_folder', '0018_auto_20201218_2242'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disposallistmodel',
            old_name='detail',
            new_name='remarks',
        ),
    ]
