# Generated by Django 2.2.7 on 2020-12-18 17:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app_folder', '0019_auto_20201219_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disposallistmodel',
            name='disposal_date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 12, 18, 17, 37, 11, 763548, tzinfo=utc), null=True, verbose_name='廃棄日'),
        ),
    ]
