# Generated by Django 2.2.7 on 2020-12-21 16:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app_folder', '0021_auto_20201221_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booklistmodel',
            name='date',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='出版年'),
        ),
        migrations.AlterField(
            model_name='booklistmodel',
            name='isbn',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='ISBN'),
        ),
        migrations.AlterField(
            model_name='disposallistmodel',
            name='date',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='発行年'),
        ),
        migrations.AlterField(
            model_name='disposallistmodel',
            name='disposal_date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 12, 21, 16, 10, 46, 111858, tzinfo=utc), null=True, verbose_name='廃棄日'),
        ),
        migrations.AlterField(
            model_name='disposallistmodel',
            name='isbn',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='ISBN'),
        ),
    ]
